# version: "3.8"

# services:
#   my-php-app:
#     image: php:7.4-cli
#     ports:
#       - 80:80
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html/
#     environment:
#       MYSQL_HOST: localhost
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#       MYSQL_DB: test_add_note

#   mysql:
#     image: mysql:5.7
#     ports:
#       - 3000:3000
#     volumes:
#       - test_add_note:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: root

# volumes:
#   test_add_note:

  # Use root/example user/password credentials
# version: '3.1'

# services:
#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 80:80
#     volumes:
#       - .:/var/www/html/

#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080 /Applications/MAMP/htdocs/docker_php/Controller


version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
    - ./db/test_add_note:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_add_note

volumes:
  test_add_note: